# Generated by Django 3.1.3 on 2021-02-05 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NGym_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Calories',
            new_name='Calories1',
        ),
    ]
